name: underwater_laser_env
channels:
  - conda-forge
dependencies:
  - python=3.9                             # Meep & PyFoam need ≲3.10
  - numpy=1.23
  - matplotlib=3.6
  - pandas=1.4
  - h5py=3.7
  - mpi4py=3.1
  - pymeep=1.25          # Python bindings for Meep
  - pymeep-extras       # MPI/HDF5 support
  - pip                                    # so we can pip-install PyFoam
  - pip:
      - PyFoam                    # install PyFoam from PyPI
